#!/bin/bash

save_nic_info() {
  local br=$1
  local nic=$2
  local nic2=$3
  local vrf=
  local ip=
  local gw=

  if [ "${nic}" ==  "eth0" ]; then
    vrf="vrf mgmt"
  fi

  ip=$( ip -br addr ls ${nic} | awk '{print $3}' )
  echo ${ip} > /tmp/${nic}.ip
  gw=$( ip -br route ls default ${vrf} | awk '{print $3}' )
  echo ${gw} > /tmp/${nic}.gw

  # net0
  ip link add ${br} type bridge
  if [ "${nic}" == "eth0" ]; then
    ip link set ${br} up mtu 1460 master mgmt
  else
    ip link set ${br} up mtu 1460
  fi
  
  #save_nic_info eth0
  ip addr del ${ip} dev ${nic}
  ip link set ${nic}  master ${br}
  ip link set ${nic2} master ${br} mtu 1460 up

}

create_setup_script() {
cat > /mnt/setup.sh << EOF
#!/bin/bash

# mgmt vrf
ip link add mgmt type vrf table 40
ip link set mgmt up

# ens3
ip addr add $(cat /tmp/eth0.ip) dev ens3
ip link set ens3 master mgmt mtu 1460
ip route add default via $(cat /tmp/eth0.gw) vrf mgmt

# ens4
ip addr add $(cat /tmp/eth1.ip) dev ens4
ip route add default via $(cat /tmp/eth1.gw)

echo '$(cat /etc/resolv.conf)' > /etc/resolv.conf
EOF

}

save_nic_info net0 eth0 ens0
save_nic_info net1 eth1 ens1
create_setup_script
