FROM        quay.io/centos/centos:stream8
ENV         container docker
ENV         TERM=linux

RUN         ln -sfv /usr/share/zoneinfo/America/Toronto /etc/localtime                               && \
            yum -y install yum-utils vim-enhanced git rsync epel-release passwd tcpdump crontabs     && \
            yum -y install iputils htop unzip less ruby procps diffutils iptables glibc-langpack-en  && \
            yum -y install iproute nc nmap sudo openssh-server openssh-clients python39              && \
            yum -y install https://rpm.frrouting.org/repo/frr-stable-repo-1-0.el8.noarch.rpm         && \
            yum -y install frr frr-pythontools && systemctl enable frr.service                       && \
            pip3 install pre-commit numpy requests ansible && echo "root:secret" | chpasswd          && \
            echo alias vi='/usr/bin/vim' >> /root/.bashrc_alias                                      && \
            systemctl disable NetworkManager
COPY        frr.service /etc/systemd/system/frr.service

RUN        echo '. /etc/bashrc.kali' >> /etc/bashrc
COPY       bashrc.kali /etc/bashrc.kali

ENTRYPOINT  ["/usr/lib/systemd/systemd"]
