FROM        ctlabs/qemu/base:latest

ENV         QEMU_IMG=CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
COPY        CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2 /media/

ENTRYPOINT  ["/bin/systemd"]
