base: centos9_img debian12_img kali_img parrot_img qemu_img
	
centos9_img:
	cd centos/c9 && make

debian12_img:
	cd debian/d12 && make

kali_img:
	cd kali && make

parrot_img:
	cd parrot && make

qemu_img:
	cd qemu && make
