#!/bin/bash

down() {
  local br=$1
  local nic=$2
  local ip=$( cat /tmp/$nic.ip )
  local gw=$( cat /tmp/$nic.gw )
  local vrf=

  if [ "$nic" == "eth0" ]; then
    vrf="vrf mgmt"
    ip link set eth0 master mgmt
  fi

  ip link del $br
  ip addr add ${ip} dev $nic
  ip route add default via ${gw} ${vrf}
}

down net0 eth0
down net1 eth1
